title: Cavanaugh Lab Group
theme: jekyll-theme-minimal
description: Exploring the dynamics of coastal and marine ecosystems through advanced remote sensing.
baseurl: "" # If your site is at the root, this should be empty.
url: "" # This should be "https://cavanaugh-lab-group.github.io" if your repository is named as such.
