# Site Build Settings and text
title: "Cavanaugh Lab Group"
author: "University of California Los Angeles, Geography Department"

# Build settings and jekyll-paginate configuration
paginate: 5
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Uncomment for RSS 2.0
# feed:
#   path: rss-feed.xml

