title: Cavanaugh Lab Group
description: Exploring the dynamics of coastal and marine ecosystems through advanced remote sensing.
baseurl: ""  # This should be empty unless you are placing your site in a folder
url: "https://cavanaugh-lab-group.github.io"

markdown: kramdown
theme: minima  # Replace with any theme supported by GitHub Pages

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
