title: Cavanaugh Lab Group
description: Exploring the dynamics of coastal and marine ecosystems through advanced remote sensing.
baseurl: ""  # Add this only if your site is located in a subpath
url: "https://cavanaugh-lab-group.github.io"  # Replace with your site's base URL
