github_username: cavanaugh-lab-group
title: Cavanaugh Lab Group
description: Exploring the dynamics of coastal and marine ecosystems through remote sensing techniques.
baseurl: ""  # This should be empty unless you are placing your site in a folder
url: "https://cavanaugh-lab-group.github.io"
markdown: kramdown
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock

include:
  - .htaccess

permalink: /:categories/:year/:month/:day/:title/
