# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
menu:
menu:
- {name: 'Research',  url: 'research'}
- {name: 'People', url: 'people'}
- {name: 'Collaborators', url: 'collaborators'}
- {name: 'Datasets', url: 'datasets'}
- {name: 'Gallery', url: 'gallery'}
- {name: 'Contact', url: 'contact'}  

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:loriberberian@ucla.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
