# Theme settings and custom text
title: "Cavanaugh Lab Group"
email: "your-email@example.com"
description: "The Cavanaugh Lab focuses on understanding the ecological impacts of climate change on coastal and marine ecosystems, including kelp forests and mangrove habitats, through remote sensing, ecological modeling, and field observations."
author:
  name: "University of California Los Angeles, Geography Department"
  email: "your-email@example.com"
  bio: "A brief bio about your lab."
  picture: "/assets/img/your-picture.jpg"

# Social media links
social:
  twitter: your-twitter-username
  github: your-github-username
  linkedin: your-linkedin-username
  disqus:
    shortname: your-disqus-shortname

# Menu items
menu:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Collaborators"
    url: "/collaborators/"
  - name: "Datasets"
    url: "/datasets/"
  - name: "People"
    url: "/people/"
  - name: "Pictures"
    url: "/pictures/"
  - name: "Research"
    url: "/research/"
  - name: "Contact"
    url: "/contact/"