# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
menu:
- {name: 'Research',  url: '2016-04-04-about-the-author'}
- {name: 'People', url: '2016-05-05-learning-resources'}
- {name: 'Collaborators', url: '2016-09-09-text-formatting'}
- {name: 'Datasets', url: '2016-10-10-getting-started'}
- {name: 'Gallery', url: '2017-01-01-welcome-to-millennial'}
- {name: 'Contact', url: 'contact'}  

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:loriberberian@ucla.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

post_date_prefix: 'Written on'
